[tool.poetry]
name = "jupyterlite"
version = "0.1.0"
description = ""
authors = ["kahnwong <karn@karnwong.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

# jupyter
ipyleaflet = "^0.18.2"
jupyterlab-geojson = "^3.4.0"
jupyterlab = "^4.2.0"
jupyterlite-core = "^0.2.3"
jupyterlite-pyodide-kernel = "^0.2.1"

# libs
pandas = "^2.2.0"
numpy = "^1.26.3"
matplotlib = "^3.8.2"
pydantic = "^2.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
