[tool.poetry]
name = "jupyterlite"
version = "0.1.0"
description = ""
authors = ["kahnwong <karn@karnwong.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ipyleaflet = "0.17.3"
jupyterlab-geojson = "3.4.0"
jupyterlab = "3.5.1"
jupyterlite-core = "0.1.0"
jupyterlite-pyodide-kernel = "0.1.2"
matplotlib = "3.7.1"
numpy = "1.24.3"
pandas = "2.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
