[tool.poetry]
name = "jupyterlite"
version = "0.1.0"
description = ""
authors = ["kahnwong <karn@karnwong.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ipyleaflet = "0.17.4"
jupyterlab-geojson = "3.4.0"
jupyterlab = "4.0.6"
jupyterlite-core = "0.1.2"
jupyterlite-pyodide-kernel = "0.1.2"
matplotlib = "3.8.0"
numpy = "1.26.2"
pandas = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
